development:
  adapter: postgresql
  encoding: unicode
  database: kj
  pool: 5
  host: localhost
  username: postgres
  password: admin
  port: 5432
  encoding: utf-8



production:
  adapter: postgresql
  host: <%= ENV['DB_HOST'] %>
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  pool: 5
  port: 5432
  username: <%= ENV['DB_USERNAME'] %>
  password:  <%= ENV['DB_USER_PASSWORD'] %>
